12-04-2025 13:44:23,Error al conectar a la Base de Datos:Unable to connect to any of the specified MySQL hosts.
12-04-2025 13:50:42,Error al obtener la información:Referencia a objeto no establecida como instancia de un objeto.
12-04-2025 13:52:25,Error al conectar a la Base de Datos:Unable to connect to any of the specified MySQL hosts.
12-04-2025 13:55:53,Error al obtener la información:Unknown column 'dse.defect' in 'field list'
14-04-2025 09:44:44,Error al obtener la información:Unknown column 'dpt.line' in 'where clause'
